{
 "title": "Grafana template",
 "tags": [
  "IBC",
  "Hermes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Hermes Grafana Dashboard\n\nhttp://hermes.informal.systems/documentation/telemetry/operators.html to learn more about the metrics."
   }
  },
  {
   "title": "Hermes logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/hermes.log\"}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 }, "options": { "content": "# Is hermes active ?" } },
  {
   "title": "client_updates_submitted over 1 minute",
   "type": "timeseries",
   "description": "Indicates if clients are getting updated.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "delta(client_updates_submitted_total{job=\"hermes\"}[1m])",
     "legendFormat": "{{src_chain}} -> {{dst_chain}}:{{client}} ({{instance}})"
    }
   ]
  },
  {
   "title": "messages_submitted over 1 minute",
   "type": "timeseries",
   "description": "Indicates if Hermes is submitting messages to a specific chain ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "delta(messages_submitted_total{job=\"hermes\"}[1m])",
     "legendFormat": "{{instance}}:{{chain}}"
    }
   ]
  },
  {
   "title": "Gas variation over 1 minute",
   "type": "timeseries",
   "description": "Indicates if you are spending gas and how much you are spending.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "delta(wallet_balance{job=\"hermes\"}[1m])",
     "legendFormat": "{{chain}}: {{account}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Current number of workers",
   "type": "timeseries",
   "description": "This panel indicates which type of workers are active for every instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "workers{job=\"hermes\"}",
     "legendFormat": "{{instance}}:{{type}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 },
   "options": {
    "content": "# Are transaction successful ?\n"
   }
  },
  {
   "title": "Oldest pending packets",
   "type": "table",
   "description": "Represents the sequence number and the date of the oldest pending packet. Use this metric to identify stuck packets.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "backlog_oldest_sequence{job=\"hermes\"}",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}} ({{instance}})"
    },
    {
     "expr": "backlog_latest_update_timestamp{job=\"hermes\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total number of send_packets_events on backlog_size",
   "type": "timeseries",
   "description": "Indicates how many packets are being processed by Hermes. If this value stays constantly more than 0, it could mean that a packet is stuck.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "backlog_size{job=\"hermes\"}",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}} ({{instance}})"
    }
   ]
  },
  {
   "title": "receive_packets_confirmed over 5 minute",
   "type": "timeseries",
   "description": "Indicates how many `receive_packets` were processed by Hermes. It can be used with `send_packet_events` as every `send_packet_event` should trigger the processing of a `receive_packet`.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "delta(receive_packets_confirmed_total{job=\"hermes\"}[5m])",
     "legendFormat": "{{src_chain}}:{{src_channel}}/{{src_port}} ({{instance}})"
    }
   ]
  },
  {
   "title": "timeout_packets_confirmed over 5 minute",
   "type": "timeseries",
   "description": "Indicates how many `timeout_packets` were processed by the relayer. It can be used with `timeout_packet_events` as every `timeout_event` should be processed by Hermes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "delta(timeout_packets_confirmed_total{job=\"hermes\"}[5m])",
     "legendFormat": "{{src_chain}}:{{src_channel}}/{{src_port}} ({{instance}})"
    }
   ]
  },
  {
   "title": "acknowledgment_packets_confirmed over 5 minute",
   "type": "timeseries",
   "description": "Indicates how many acknowledgements were processed by the relayer. It can be used with `acknowledgment_events` as every event should be processed by Hermes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "delta(acknowledgment_packets_confirmed_total{job=\"hermes\"}[5m])",
     "legendFormat": "{{src_chain}}:{{src_channel}}/{{src_port}} ({{instance}})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 61 },
   "options": {
    "content": "# What is the overall IBC status of each network?\r\n\r\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "send_packets_events over 5 minute",
   "type": "timeseries",
   "description": "Indicates the number of  `send_packet_event` observed.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "delta(send_packet_events_total{job=\"hermes\"}[5m])",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}} ({{instance}})"
    }
   ]
  },
  {
   "title": "acknowledgement_events over 5 minute",
   "type": "timeseries",
   "description": "Indicates the number of  `acknowledgement_event` observed.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
   "targets": [
    {
     "expr": "delta(acknowledgement_events_total{job=\"hermes\"}[5m])",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}} ({{instance}})"
    }
   ]
  },
  {
   "title": "timeout_events over 5 minute",
   "type": "timeseries",
   "description": "Indicates the number of  `timeout_event` observed.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 63 },
   "targets": [
    {
     "expr": "delta(timeout_events_total{job=\"hermes\"}[5m])",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}} ({{instance}})"
    }
   ]
  },
  {
   "title": "ws_events received over 1 minute",
   "type": "timeseries",
   "description": "Indicates the number of  `event` observed via the websocket subscription.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "delta(ws_events_total{job=\"hermes\"}[1m])",
     "legendFormat": "{{instance}}:{{chain}}"
    }
   ]
  },
  {
   "title": "ws_reconnect over 1 minute",
   "type": "timeseries",
   "description": "Indicates the number of times Hermes reconnected to the websocket.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
   "targets": [
    {
     "expr": "delta(ws_reconnect_total{job=\"hermes\"}[1m])",
     "legendFormat": "{{instance}}:{{chain}}"
    }
   ]
  },
  {
   "title": "RPC queries sent over 1 minute",
   "type": "timeseries",
   "description": "Indicate the number of queries per instance and chain.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
   "targets": [
    {
     "expr": "sum(delta(queries_total{job=\"hermes\"}[1m])) by(instance,chain)",
     "legendFormat": "{{instance}}:{{chain}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 79 },
   "options": {
    "content": "# How efficient and how secure is the IBC status on each network ?\n\n"
   }
  },
  {
   "title": "cleared_acknowledgment_events over 5 minute",
   "type": "timeseries",
   "description": "Cleared `acknowledgment_events` rate per path. It is an indication that IBC packet relaying may be unsuccessful and that Hermes periodically finds packets to clear (i.e., unblock).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "delta(cleared_acknowledgment_events_total{job=\"hermes\"}[5m])",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}} ({{instance}})"
    }
   ]
  },
  {
   "title": "cleared_send_packet_events over 5 minute",
   "type": "timeseries",
   "description": "Cleared `send_packet_events` rate per path. It is an indication that IBC packet relaying may be unsuccessful and that Hermes periodically finds packets to clear (i.e., unblock).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "delta(cleared_send_packet_events_total{job=\"hermes\"}[5m])",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}} ({{instance}})"
    }
   ]
  },
  {
   "title": "95th quantile of tx_latency_submitted rate over 5 minutes",
   "type": "timeseries",
   "description": "Indicates the latency rate for all transactions submitted to each chain.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, chain, instance) (rate(tx_latency_submitted_bucket[5m])))",
     "legendFormat": "{{instance}}:{{chain}}"
    }
   ]
  },
  {
   "title": "queries_cache_hits over 1 minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "sum by(chain, instance) (delta(queries_cache_hits_total{job=\"hermes\"}[1m]))",
     "legendFormat": "{{instance}}:{{chain}}"
    }
   ]
  },
  {
   "title": "tx_latency_submitted histogram oraibtc-testnet-1",
   "type": "bargauge",
   "description": "Indicates the latency rate for all transactions submitted from oraibtc-testnet-1",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tx_latency_submitted_bucket{chain=\"oraibtc-testnet-1\"}[$__range])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "tx_latency_confirmed_bucket histogram oraibtc-testnet-1",
   "type": "bargauge",
   "description": "Indicates the latency rate for all transactions confirmed from oraibtc-testnet-1",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tx_latency_confirmed_bucket{chain=\"oraibtc-testnet-1\"}[$__range])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 106 }, "options": { "content": "# Extra" } },
  {
   "title": "client_misbehaviours_submitted over 5 minutes",
   "type": "timeseries",
   "description": "If `misbehaviour = true` then hermes will detect misbehaviours from clients and stop relaying to this client if one is detected. It is possible to set an alarm on this. ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "delta(client_misbehaviours_submitted_total[5m])",
     "legendFormat": "{{src_chain}}-{{dst_chain}}:{{client}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Physical Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-(node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes))*100",
     "legendFormat": "RAM Usage"
    }
   ]
  },
  {
   "title": "Data Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total[1d]))"
    }
   ]
  },
  {
   "title": "Data Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total[1d]))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes{}" }
   ]
  },
  {
   "title": "Total Swap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_SwapTotal_bytes{}" }
   ]
  },
  {
   "title": "Data Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total[2w]))"
    }
   ]
  },
  {
   "title": "Data Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total[2w]))"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  {
   "title": "Free Swap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_SwapFree_bytes" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (mode,cpu) (\n  1 - rate(node_cpu_seconds_total{mode=\"idle\"}[1m])\n)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-(node_memory_SwapFree_bytes/node_memory_SwapTotal_bytes))*100",
     "legendFormat": "Swap Usage"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 123 }, "options": { "content": "# Chain Info" } },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tendermint_consensus_height" }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tendermint_consensus_num_txs[24h]))"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "tendermint_mempool_size" }
   ]
  },
  {
   "title": "Avg Block Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "3600/delta(tendermint_consensus_height[1h])"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power",
     "legendFormat": "Online"
    },
    {
     "expr": "tendermint_consensus_missing_validators_power",
     "legendFormat": "Missing"
    },
    {
     "expr": "tendermint_consensus_byzantine_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Byzantine"
    }
   ]
  }
 ]
}